/// <reference types="vite/client" />

declare module '*.vue' {
  import type { DefineComponent } from 'vue'
  const component: DefineComponent<object, object, unknown>
  export default component
}

// Nuxt build-time module stubs (generated by @nuxt/ui Vite plugin)
declare module '#build/ui' {
  const ui: Record<string, unknown>
  export default ui
}

declare module '#build/ui/*' {
  const theme: Record<string, unknown>
  export default theme
}

declare module '#build/nuxt-icon-client-bundle' {
  const icons: Record<string, unknown>
  export default icons
}

declare module '#build/app.config' {
  const config: Record<string, unknown>
  export default config
}
